### ISSUE TITLE
Error when release step

### ISSUE THREAD

**Issue by redknotmiaoyuqiao** [mmozeiko/build-dawn#1]
First, Thank you for your job. 

I get some error when I fork this project and run actions

![image](https://github.com/mmozeiko/build-dawn/assets/5202941/92739ebb-496a-40ed-9dc5-fb00ea796d03)

https://github.com/redknotmiaoyuqiao/build-dawn/actions/runs/5466220129/jobs/9950819135

Could you help me? Thank you~~~

**Comment by mmozeiko** [comment]
By default GitHub Actions does not have permission to modify repository. If you want it to be able to create releases, you need to go to project Settings -> Actions -> General and allow "Read and write permissions" for workflows.

**Comment by redknotmiaoyuqiao** [comment]
Thank you very mach.   I try to fix it, But I get another error in "build" step

<img width="1271" alt="截屏2023-07-06 下午8 26 04" src="https://github.com/mmozeiko/build-dawn/assets/5202941/ed388e14-864e-43e7-9c59-ac3550535aa4">

I think it is an error about Dawn itself, looks like some http link counldn`t use anymore.

do you know what happened ?


Thank you very much again

**Comment by redknotmiaoyuqiao** [comment]
![image](https://github.com/mmozeiko/build-dawn/assets/5202941/33db62be-4366-4c22-a597-b3c119d63534)
 Success !! Thank You Very Much!!!
