### ISSUE TITLE
Binaries became much larger with 2024-11-17

### ISSUE THREAD

**Issue by EricGrange** [mmozeiko/build-dawn#4]
Starting with 2024-11-17 build, the binaries became much larger, going for instance with x64 dll from about 5.8 MB to 8 MB.
I check the dawn changelog (https://dawn.googlesource.com/dawn/+log) but did not spot anything obvious that would explain it.

Just creating the issue to make sure the size increased does not arise from a build issue :)

**Comment by mmozeiko** [comment]
I've added option to use SPIR-V shaders as input. This means linking in SPIR-V dependencies.

See https://gist.github.com/mmozeiko/4c68b91faff8b7026e8c5e44ff810b62#file-win32_webgpu-c-L354-L373 for example.

**Comment by EricGrange** [comment]
Oh, that's great! Thanks.
